/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmkmRouteImport } from './routes/umkm'
import { Route as TimRouteImport } from './routes/tim'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as KampungRouteImport } from './routes/kampung'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KampungIndexRouteImport } from './routes/kampung.index'
import { Route as KampungSlugRouteImport } from './routes/kampung.$slug'

const UmkmRoute = UmkmRouteImport.update({
  id: '/umkm',
  path: '/umkm',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const KampungRoute = KampungRouteImport.update({
  id: '/kampung',
  path: '/kampung',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KampungIndexRoute = KampungIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KampungRoute,
} as any)
const KampungSlugRoute = KampungSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KampungRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kampung': typeof KampungRouteWithChildren
  '/peta': typeof PetaRoute
  '/profil': typeof ProfilRoute
  '/tim': typeof TimRoute
  '/umkm': typeof UmkmRoute
  '/kampung/$slug': typeof KampungSlugRoute
  '/kampung/': typeof KampungIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/peta': typeof PetaRoute
  '/profil': typeof ProfilRoute
  '/tim': typeof TimRoute
  '/umkm': typeof UmkmRoute
  '/kampung/$slug': typeof KampungSlugRoute
  '/kampung': typeof KampungIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kampung': typeof KampungRouteWithChildren
  '/peta': typeof PetaRoute
  '/profil': typeof ProfilRoute
  '/tim': typeof TimRoute
  '/umkm': typeof UmkmRoute
  '/kampung/$slug': typeof KampungSlugRoute
  '/kampung/': typeof KampungIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/kampung'
    | '/peta'
    | '/profil'
    | '/tim'
    | '/umkm'
    | '/kampung/$slug'
    | '/kampung/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/peta'
    | '/profil'
    | '/tim'
    | '/umkm'
    | '/kampung/$slug'
    | '/kampung'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/kampung'
    | '/peta'
    | '/profil'
    | '/tim'
    | '/umkm'
    | '/kampung/$slug'
    | '/kampung/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  KampungRoute: typeof KampungRouteWithChildren
  PetaRoute: typeof PetaRoute
  ProfilRoute: typeof ProfilRoute
  TimRoute: typeof TimRoute
  UmkmRoute: typeof UmkmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/umkm': {
      id: '/umkm'
      path: '/umkm'
      fullPath: '/umkm'
      preLoaderRoute: typeof UmkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampung': {
      id: '/kampung'
      path: '/kampung'
      fullPath: '/kampung'
      preLoaderRoute: typeof KampungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampung/': {
      id: '/kampung/'
      path: '/'
      fullPath: '/kampung/'
      preLoaderRoute: typeof KampungIndexRouteImport
      parentRoute: typeof KampungRoute
    }
    '/kampung/$slug': {
      id: '/kampung/$slug'
      path: '/$slug'
      fullPath: '/kampung/$slug'
      preLoaderRoute: typeof KampungSlugRouteImport
      parentRoute: typeof KampungRoute
    }
  }
}

interface KampungRouteChildren {
  KampungSlugRoute: typeof KampungSlugRoute
  KampungIndexRoute: typeof KampungIndexRoute
}

const KampungRouteChildren: KampungRouteChildren = {
  KampungSlugRoute: KampungSlugRoute,
  KampungIndexRoute: KampungIndexRoute,
}

const KampungRouteWithChildren =
  KampungRoute._addFileChildren(KampungRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  KampungRoute: KampungRouteWithChildren,
  PetaRoute: PetaRoute,
  ProfilRoute: ProfilRoute,
  TimRoute: TimRoute,
  UmkmRoute: UmkmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
